// <auto-generated />
namespace Project.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class V0002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V0002));
        
        string IMigrationMetadata.Id
        {
            get { return "202108280728316_V0002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
