// <auto-generated />
namespace Project.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class LogImplement001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LogImplement001));
        
        string IMigrationMetadata.Id
        {
            get { return "202109080938041_LogImplement001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
