// <auto-generated />
namespace Project.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Exception003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exception003));
        
        string IMigrationMetadata.Id
        {
            get { return "202109090639247_Exception003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
